# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

variables:
  global_variable: '$(Sonartype.somevariable)'

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

name: $(BuildID)
steps:
steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'echo $Sonartype.somevariable'

- task: Maven@3
  inputs:
    mavenPomFile: './nexuse2e-parent/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean package'
