name: $(BuildID)
trigger:
  batch: false
  branches:
    exclude:
      - '*'
  tags:
    include:
      - 'v*'
stages:
  - stage: Build
    jobs:
      - job: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: MavenAuthenticate@0
            name: authenticate_feeds
            inputs:
              artifactsFeeds: 'org.nexuse2e, org.nexuse2e-snapshots'
          - task: Maven@3
            name: Install_Parent
            inputs:
              mavenPomFile: ./nexuse2e-parent/pom.xml
              goals: clean install
              options: >
                -B -e --no-transfer-progress 
              publishJUnitResults: false
              javaHomeOption: JDKVersion
              jdkVersionOption: 1.8
              jdkArchitectureOption: 'x64'
              mavenOptions: '-Xmx3072m'
              mavenAuthenticateFeed: true
          - task: Maven@3
            name: Build_core
            inputs:
              mavenPomFile: ./nexuse2e-core/pom.xml
              goals: clean deploy
              options: >
                -B -e --no-transfer-progress
                -Dmaven.wagon.http.ssl.insecure=true
                -Dmaven.wagon.http.ssl.allowall=true
              publishJUnitResults: false
              javaHomeOption: JDKVersion
              jdkVersionOption: 1.8
              jdkArchitectureOption: 'x64'
              mavenOptions: '-Xmx3072m'
              mavenAuthenticateFeed: true
          - task: CopyPublishBuildArtifacts@1
            inputs:
              Contents: 'nexuse2e-core/target/*.jar'
              ArtifactName: 'core'
              ArtifactType: 'Container'
          - task: CopyPublishBuildArtifacts@1
            inputs:
              Contents: 'nexuse2e-webapp/target/*.war'
              ArtifactName: 'webapp'
              ArtifactType: 'Container'
          - task: GitHubRelease@1
            inputs:
              gitHubConnection: 'GitHub - Serranya'
              repositoryName: 'solutionsdirekt/NEXUSe2e'
              action: 'create'
              target: '$(Build.SourceVersion)'
              tagSource: 'gitTag'
              isDraft: true
              addChangeLog: false
